In [166]:
import pandas as pd

In [167]:
pd.set_option('display.max_columns', None)

In [168]:
df1 = pd.read_csv('Pre-test+1_August+31,+2024_17.24.csv')
df1.drop([0,1], inplace=True)
df1 = df1[pd.to_datetime(df1['StartDate'], format='%Y-%m-%d %H:%M:%S') > pd.to_datetime('2024-08-23')]
df1.drop(columns=['StartDate','EndDate','Progress','Finished','Status','IPAddress','RecordedDate','ResponseId',
                  'RecipientLastName','RecipientFirstName','RecipientEmail','ExternalReference','LocationLatitude',
                  'LocationLongitude','DistributionChannel','UserLanguage'], axis=1, inplace=True)

applications = ['Gmail', 'Google Calendar', 'Google Drive', 'Google Maps', 'Google Tasks', 'None', 'Other (input)']
for app in applications:
    name = {
        'Gmail': 'pre_usage_gmail',
        'Google Calendar': 'pre_usage_calendar',
        'Google Drive': 'pre_usage_drive',
        'Google Maps': 'pre_usage_maps',
        'Google Tasks': 'pre_usage_tasks',
        'None': 'pre_usage_none',
        'Other (input)': 'pre_usage_other'
    }.get(app)
    df1[name] = df1['Q1'].apply(lambda x: 1 if app in x else 0)
df1.drop(columns=['Q1'], inplace=True)

df1.Q1_6_TEXT.fillna('', inplace=True)
df1['Q1_6_TEXT'] = df1['Q1_6_TEXT'].apply(lambda x: ','.join([v for v in x.split(',') if 'chrome' not in v.lower()]))

# df1['Q2'].replace('1 hour or less', 1, inplace=True)

challenges = ['Time management', 'Coordination with team members', 'Repetitive tasks', 'Prioritization', 'Not facing any challenges', 'Other (input)']
for challenge in challenges:
    name = {
        'Time management': 'pre_challenge_timemanagement',
        'Coordination with team members': 'pre_challenge_coordination',
        'Repetitive tasks': 'pre_challenge_repetitive',
        'Prioritization': 'pre_challenge_prioritization',
        'Not facing any challenges': 'pre_challenge_none',
        'Other (input)': 'pre_challenge_other'
    }.get(challenge)
    df1[name] = df1['Q8'].apply(lambda x: 1 if challenge in x else 0)
df1.drop(columns=['Q8'], inplace=True)

planned_help = ['Automating repetitive tasks', 'Providing task recommendations', 'Assisting in task prioritization', 'Don\'t know', 'Other (input)']
for help in planned_help:
    name = {
        'Automating repetitive tasks': 'pre_help_automating_repetitive_tasks',
        'Providing task recommendations': 'pre_help_providing_task_recommendations',
        'Assisting in task prioritization': 'pre_help_assisting_in_task_prioritization',
        'Don\'t know': 'pre_help_dont_know',
        'Other (input)': 'pre_help_other'
    }.get(help)
    df1[name] = df1['Q14'].apply(lambda x: 1 if help in x else 0)
df1.drop(columns=['Q14'], inplace=True)

benefits = ['Increased productivity', 'Better task organization', 'Time savings', 'Reduced workload', 'Other (input)']
for benefit in benefits:
    name = {
        'Increased productivity': 'pre_benefit_increased_productivity',
        'Better task organization': 'pre_benefit_better_task_organization',
        'Time savings': 'pre_benefit_time_savings',
        'Reduced workload': 'pre_benefit_reduced_workload',
        'Other (input)': 'pre_benefit_other'
    }.get(benefit)
    df1[name] = df1['Q16'].apply(lambda x: 1 if benefit in x else 0)
df1.drop(columns=['Q16'], inplace=True)

foreseen_challenges = ['Learning curve', 'Trust in AI\'s abilities', 'Integration with existing tools/systems', 'Privacy/security concerns', 'Other (input)']
for challenge in foreseen_challenges:
    name = {
        'Learning curve': 'pre_foreseen_challenge_learning_curve',
        'Trust in AI\'s abilities': 'pre_foreseen_challenge_trust_in_AI_abilities',
        'Integration with existing tools/systems': 'pre_foreseen_challenge_integration_with_existing_tools',
        'Privacy/security concerns': 'pre_foreseen_challenge_privacy_security_concerns',
        'Other (input)': 'pre_foreseen_challenge_other'
    }.get(challenge)
    df1[name] = df1['Q20'].apply(lambda x: 1 if challenge in x else 0)
df1.drop(columns=['Q20'], inplace=True)

ordered = ['Q11','Q29','Q30','Q30_8_TEXT','Q31','Duration (in seconds)','pre_usage_gmail','pre_usage_calendar','pre_usage_drive',
           'pre_usage_maps','pre_usage_tasks','pre_usage_none','pre_usage_other','Q1_6_TEXT','Q2','Q4','Q7','Q33','Q34','Q35','Q36',
           'pre_challenge_timemanagement','pre_challenge_coordination','pre_challenge_repetitive','pre_challenge_prioritization',
           'pre_challenge_none','pre_challenge_other','Q8_6_TEXT','Q9','Q37','Q12','pre_help_automating_repetitive_tasks',
           'pre_help_providing_task_recommendations','pre_help_assisting_in_task_prioritization','pre_help_dont_know','pre_help_other',
           'Q14_4_TEXT','Q15','pre_benefit_increased_productivity','pre_benefit_better_task_organization','pre_benefit_time_savings',
           'pre_benefit_reduced_workload','pre_benefit_other','Q16_5_TEXT','Q18','Q19','pre_foreseen_challenge_learning_curve',
           'pre_foreseen_challenge_trust_in_AI_abilities','pre_foreseen_challenge_integration_with_existing_tools',
           'pre_foreseen_challenge_privacy_security_concerns','pre_foreseen_challenge_other','Q20_5_TEXT','Q23_1','Q23_2','Q23_3',
           'Q23_4','Q23_5','Q24','Q26','Q27']
df1 = df1[ordered + [ col for col in df1.columns if col not in ordered]]

df1.rename(columns={
    'Q11': 'prolific_id',
    'Duration (in seconds)': 'pre_duration',
    'Q29': 'gender',
    'Q30': 'ethnicity',
    'Q30_8_TEXT': 'ethnicity_other',
    'Q31': 'age',
    'Q1_6_TEXT': 'pre_usage_other_details',
    'Q2': 'pre_hours_per_day',
    'Q4': 'pre_activities',
    'Q7': 'pre_usage_gmail_easy',
    'Q33': 'pre_usage_calendar_easy',
    'Q34': 'pre_usage_drive_easy',
    'Q35': 'pre_usage_maps_easy',
    'Q36': 'pre_usage_tasks_easy',
    'Q8_6_TEXT': 'pre_challenge_other_details',
    'Q9': 'pre_used_automation_was_convenient',
    'Q37': 'pre_comfortable_with_idea_of_automation',
    'Q12': 'pre_always_use_AI_if_possible',
    'Q14_4_TEXT': 'pre_help_other_details',
    'Q15': 'pre_used_LLM',
    'Q16_5_TEXT': 'pre_benefit_other_details',
    'Q18': 'pre_expectations',
    'Q19': 'pre_used_ai_task_management_agents',
    'Q20_5_TEXT': 'pre_foreseen_challenge_other_details',
    'Q23_1': 'pre_expertise_gmail',
    'Q23_2': 'pre_expertise_calendar',
    'Q23_3': 'pre_expertise_drive',
    'Q23_4': 'pre_expertise_maps',
    'Q23_5': 'pre_expertise_tasks',
    'Q24': 'pre_expertise_chatgpt',
    'Q26': 'pre_used_chatgpt_to_accomplish_tasks',
    'Q27': 'pre_used_chatgpt_purpose'
}, inplace=True)

df1.ethnicity_other.fillna('', inplace=True)
df1.pre_challenge_other_details.fillna('', inplace=True)
df1.pre_used_automation_was_convenient.fillna('', inplace=True)
df1.pre_help_other_details.fillna('', inplace=True)
df1.pre_used_LLM.replace({'Yes': 1, 'No': 0}, inplace=True)
df1.pre_benefit_other_details.fillna('', inplace=True)
df1.pre_used_ai_task_management_agents.replace({'Yes': 1, 'No': 0}, inplace=True)
df1.pre_foreseen_challenge_other_details.fillna('', inplace=True)
df1.pre_used_chatgpt_purpose.fillna('', inplace=True)

df1 = df1.astype({
    'prolific_id': 'string',
    'gender': 'category',
    'ethnicity': 'category',
    'ethnicity_other': 'string',
    'age': 'category',
    'pre_duration': 'int32',
    'pre_usage_gmail': 'bool',
    'pre_usage_calendar': 'bool',
    'pre_usage_drive': 'bool',
    'pre_usage_maps': 'bool',
    'pre_usage_tasks': 'bool',
    'pre_usage_none': 'bool',
    'pre_usage_other': 'bool',
    'pre_usage_other_details': 'string',
    'pre_hours_per_day': 'category',
    'pre_activities': 'string',
    'pre_usage_gmail_easy': 'category',
    'pre_usage_calendar_easy': 'category',
    'pre_usage_drive_easy': 'category',
    'pre_usage_maps_easy': 'category',
    'pre_usage_tasks_easy': 'category',
    'pre_challenge_timemanagement': 'bool',
    'pre_challenge_coordination': 'bool',
    'pre_challenge_repetitive': 'bool',
    'pre_challenge_prioritization': 'bool',
    'pre_challenge_none': 'bool',
    'pre_challenge_other': 'bool',
    'pre_challenge_other_details': 'string',
    'pre_used_automation_was_convenient': 'category',
    'pre_comfortable_with_idea_of_automation': 'category',
    'pre_always_use_AI_if_possible': 'category',
    'pre_help_automating_repetitive_tasks': 'bool',
    'pre_help_providing_task_recommendations': 'bool',
    'pre_help_assisting_in_task_prioritization': 'bool',
    'pre_help_dont_know': 'bool',
    'pre_help_other': 'bool',
    'pre_help_other_details': 'string',
    'pre_used_LLM': 'bool',
    'pre_benefit_increased_productivity': 'bool',
    'pre_benefit_better_task_organization': 'bool',
    'pre_benefit_time_savings': 'bool',
    'pre_benefit_reduced_workload': 'bool',
    'pre_benefit_other': 'bool',
    'pre_benefit_other_details': 'string',
    'pre_expectations': 'string',
    'pre_used_ai_task_management_agents': 'bool',
    'pre_foreseen_challenge_learning_curve': 'bool',
    'pre_foreseen_challenge_trust_in_AI_abilities': 'bool',
    'pre_foreseen_challenge_integration_with_existing_tools': 'bool',
    'pre_foreseen_challenge_privacy_security_concerns': 'bool',
    'pre_foreseen_challenge_other': 'bool',
    'pre_foreseen_challenge_other_details': 'string',
    'pre_expertise_gmail': 'category',
    'pre_expertise_calendar': 'category',
    'pre_expertise_drive': 'category',
    'pre_expertise_maps': 'category',
    'pre_expertise_tasks': 'category',
    'pre_expertise_chatgpt': 'category',
    'pre_used_chatgpt_to_accomplish_tasks': 'category',
    'pre_used_chatgpt_purpose': 'string'
})

df1.head()

,prolific_id,gender,ethnicity,ethnicity_other,age,pre_duration,pre_usage_gmail,pre_usage_calendar,pre_usage_drive,pre_usage_maps,pre_usage_tasks,pre_usage_none,pre_usage_other,pre_usage_other_details,pre_hours_per_day,pre_activities,pre_usage_gmail_easy,pre_usage_calendar_easy,pre_usage_drive_easy,pre_usage_maps_easy,pre_usage_tasks_easy,pre_challenge_timemanagement,pre_challenge_coordination,pre_challenge_repetitive,pre_challenge_prioritization,pre_challenge_none,pre_challenge_other,pre_challenge_other_details,pre_used_automation_was_convenient,pre_comfortable_with_idea_of_automation,pre_always_use_AI_if_possible,pre_help_automating_repetitive_tasks,pre_help_providing_task_recommendations,pre_help_assisting_in_task_prioritization,pre_help_dont_know,pre_help_other,pre_help_other_details,pre_used_LLM,pre_benefit_increased_productivity,pre_benefit_better_task_organization,pre_benefit_time_savings,pre_benefit_reduced_workload,pre_benefit_other,pre_benefit_other_details,pre_expectations,pre_used_ai_task_management_agents,pre_foreseen_challenge_learning_curve,pre_foreseen_challenge_trust_in_AI_abilities,pre_foreseen_challenge_integration_with_existing_tools,pre_foreseen_challenge_privacy_security_concerns,pre_foreseen_challenge_other,pre_foreseen_challenge_other_details,pre_expertise_gmail,pre_expertise_calendar,pre_expertise_drive,pre_expertise_maps,pre_expertise_tasks,pre_expertise_chatgpt,pre_used_chatgpt_to_accomplish_tasks,pre_used_chatgpt_purpose
7,66c8bc6c5b8112a254c5dd9e,Female,Hispanic or Latino,,18-25,315,True,False,True,True,False,False,False,,3,"Work, school, hobby",Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,False,True,False,False,False,False,,Somewhat comfortable,Somewhat comfortable,Disagree,True,True,False,False,False,,True,True,True,True,True,False,,AI task management would help me optimize my t...,False,True,True,True,True,False,,Experienced,Beginner,Experienced,Experienced,No experience,Beginner,Yes,"I have used it to find research, answer questi..."
8,6660ad93734b2991dcb61854,Female,Caucasian or White,,50-60,305,True,True,True,False,False,False,False,,2,contacting people and writing to share,Agree,Agree,Agree,Neither agree nor disagree,Neither agree nor disagree,False,False,False,False,False,False,,Somewhat comfortable,Somewhat comfortable,Agree,True,False,False,False,False,,True,True,False,True,False,False,,Help me organize my tasks even take over some ...,False,True,False,True,False,False,,Experienced,Beginner,Intermediate,Beginner,No experience,Intermediate,Yes,"Mostly copy writing, and getting a starting pl..."
9,661433352944c111887337c4,Female,Caucasian or White,,31-39,300,True,True,True,True,False,False,False,,3,"booking client meetings, responding to and sen...",Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,False,False,False,False,False,False,,Neutral,Neutral,Agree,True,True,True,False,False,,True,True,False,True,False,False,,I expect to save a lot of time doing a task th...,True,True,False,True,False,False,,Experienced,Experienced,Experienced,Experienced,Experienced,Intermediate,Yes,ChatGPT helps me write key points from a meeti...
10,613254f907b5038999e2688f,Female,Caucasian or White,,40-49,332,True,False,True,True,False,False,False,,1 hour or less,personal,Agree,Neither agree nor disagree,Agree,Strongly agree,Neither agree nor disagree,False,False,True,True,False,False,,Somewhat comfortable,Somewhat comfortable,Agree,False,False,False,True,False,,True,False,True,True,False,False,,help get information quickly,False,False,True,False,True,False,,Intermediate,Beginner,Beginner,Experienced,No experience,Beginner,Yes,Prolofic studies
11,66882c4e8bcda7f9bf988fe1,Female,Caucasian or White,,40-49,291,True,False,False,False,False,False,True,,5,"side hustle, hobby",Strongly agree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,False,False,False,False,True,False,,Neutral,Somewhat uncomfortable,Strongly disagree,False,True,False,False,False,,True,False,False,True,False,False,,I'm honestly not sure what to expect.,False,True,False,False,False,False,,Expert,No experience,Beginner,No experience,No experience,Beginner,Yes,Entertainment

In [169]:
df1.to_csv('pre_full.csv', index=False)

In [170]:
ids = [
    '66c8bc6c5b8112a254c5dd9e',
    '613254f907b5038999e2688f',
    '5e59a1ef29132108b99fbff8',
    '612517df29cd32c6632b4a44',
    '6478edcddd5625bacfcd296a',
    '66aeea1cc3ea6ee963f7c515',
    '668aa70936b52c2937a64944',
    '65959564477c6a68a50176e4',
    '66a7e128f37f34ca658be38b',
    '66454ede84d396a8e86d5b5f'
]
df1_filtered = df1.loc[df1['prolific_id'].isin(ids)]
df1_filtered.head(100)

,prolific_id,gender,ethnicity,ethnicity_other,age,pre_duration,pre_usage_gmail,pre_usage_calendar,pre_usage_drive,pre_usage_maps,pre_usage_tasks,pre_usage_none,pre_usage_other,pre_usage_other_details,pre_hours_per_day,pre_activities,pre_usage_gmail_easy,pre_usage_calendar_easy,pre_usage_drive_easy,pre_usage_maps_easy,pre_usage_tasks_easy,pre_challenge_timemanagement,pre_challenge_coordination,pre_challenge_repetitive,pre_challenge_prioritization,pre_challenge_none,pre_challenge_other,pre_challenge_other_details,pre_used_automation_was_convenient,pre_comfortable_with_idea_of_automation,pre_always_use_AI_if_possible,pre_help_automating_repetitive_tasks,pre_help_providing_task_recommendations,pre_help_assisting_in_task_prioritization,pre_help_dont_know,pre_help_other,pre_help_other_details,pre_used_LLM,pre_benefit_increased_productivity,pre_benefit_better_task_organization,pre_benefit_time_savings,pre_benefit_reduced_workload,pre_benefit_other,pre_benefit_other_details,pre_expectations,pre_used_ai_task_management_agents,pre_foreseen_challenge_learning_curve,pre_foreseen_challenge_trust_in_AI_abilities,pre_foreseen_challenge_integration_with_existing_tools,pre_foreseen_challenge_privacy_security_concerns,pre_foreseen_challenge_other,pre_foreseen_challenge_other_details,pre_expertise_gmail,pre_expertise_calendar,pre_expertise_drive,pre_expertise_maps,pre_expertise_tasks,pre_expertise_chatgpt,pre_used_chatgpt_to_accomplish_tasks,pre_used_chatgpt_purpose
7,66c8bc6c5b8112a254c5dd9e,Female,Hispanic or Latino,,18-25,315,True,False,True,True,False,False,False,,3,"Work, school, hobby",Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,False,True,False,False,False,False,,Somewhat comfortable,Somewhat comfortable,Disagree,True,True,False,False,False,,True,True,True,True,True,False,,AI task management would help me optimize my t...,False,True,True,True,True,False,,Experienced,Beginner,Experienced,Experienced,No experience,Beginner,Yes,"I have used it to find research, answer questi..."
10,613254f907b5038999e2688f,Female,Caucasian or White,,40-49,332,True,False,True,True,False,False,False,,1 hour or less,personal,Agree,Neither agree nor disagree,Agree,Strongly agree,Neither agree nor disagree,False,False,True,True,False,False,,Somewhat comfortable,Somewhat comfortable,Agree,False,False,False,True,False,,True,False,True,True,False,False,,help get information quickly,False,False,True,False,True,False,,Intermediate,Beginner,Beginner,Experienced,No experience,Beginner,Yes,Prolofic studies
24,5e59a1ef29132108b99fbff8,Female,Caucasian or White,,26-30,253,True,True,True,True,False,False,True,Google Sheets,3,"persona life and work the most, occasionally f...",Agree,Agree,Agree,Agree,Neither agree nor disagree,False,False,False,False,False,False,,,Somewhat uncomfortable,Disagree,True,False,False,True,False,,True,False,False,True,False,False,,"I hope it will help manage some of the rote, t...",False,False,True,True,True,False,,Experienced,Intermediate,Experienced,Experienced,Beginner,Beginner,Yes,Help draft emails
30,612517df29cd32c6632b4a44,Female,Caucasian or White,,50-60,362,True,True,True,False,False,False,False,,3,"All email, calendar for personal schedule, Doc...",Agree,Agree,Agree,Neither agree nor disagree,Neither agree nor disagree,False,False,False,False,True,False,,Somewhat uncomfortable,Neutral,Strongly disagree,True,False,False,False,False,,True,False,False,True,False,False,,Hopefully anticipate my needs correctly and do...,False,False,True,False,False,False,,Experienced,Experienced,Experienced,Intermediate,No experience,Intermediate,Yes,Have conversations and ask for advice and info...
34,6478edcddd5625bacfcd296a,Female,African or Black,,50-60,799,True,False,False,False,True,False,False,,3,Work and other personal activities,Agree,Agree,Agree,Agree,Agree,False,False,False,False,False,False,,Very comfortable,Very comfortable,Agree,False,True,False,False,False,,True,True,False,False,False,False,,I expect nothing but the best,True,False,True,False,True,False,,Experienced,Experienced,Experienced,Experienced,Experienced,Beginner,Yes,I used it to generate ideas about things that ...
36,66aeea1cc3ea6ee963f7c515,Female,Caucasian or White,,50-60,519,True,True,True,True,True,False,True,,6,"Business work, daytrips (maps)",Agree,Agree,Agree,Strongly agree,Agree,False,True,False,True,False,False,,Very comfortable,Very comfortable,Neither agree nor disagree,True,True,False,False,False,,True,True,True,True,True,False,,The AI agent will help streamline some of my m...,False,True,True,True,True,False,,Experienced,Intermediate,Experienced,Experienced,Intermediate,Experienced,Yes,"rewording for memorandum language, resumes, an..."
41,668aa70936b52c2937a64944,Female,African or Black,,40-49,920,True,False,True,True,False,False,False,,4,work research,Agree,Agree,Agree,Strongly agree,Agree,False,True,True,False,False,False,,Very comfortable,Very comfortable,Agree,False,True,False,False,False,,True,False,True,True,True,False,,"to help me with better task organization, to h...",True,True,False,False,True,False,,Experienced,Beginner,Intermediate,Experienced,Beginner,Intermediate,Yes,to help in research to help save time to help...
43,65959564477c6a68a50176e4,Female,African or Black,,18-25,274,True,False,True,True,False,False,False,,8,work and volunteering,Agree,Agree,Strongly agree,Strongly agree,Neither agree nor disagree,False,True,False,True,False,False,,Very comfortable,Very comfortable,Disagree,True,True,True,False,False,,True,True,True,False,False,False,,Help make recommendations for task prioritizat...,False,True,False,False,True,False,,Expert,Expert,Expert,Expert,No experience,Beginner,Yes,editing emails and providing ideas.
47,66a7e128f37f34ca658be38b,Male,Caucasian or White,,18-25,163,True,False,True,True,True,False,False,,3,Work,Strongly agree,Agree,Disagree,Agree,Agree,False,False,False,False,False,False,,Neutral,Very comfortable,Agree,True,False,False,False,False,,True,True,False,False,False,False,,Come up with action items and streamline my wo...,False,False,True,False,False,False,,Experienced,Intermediate,Intermediate,Experienced,Experienced,Beginner,No,
55,66454ede84d396a8e86d5b5f,Male,African or Black,,18-25,844,True,False,False,True,False,False,False,,1 hour or less,"to search for information, and GPS Location. a...",Agree,Neither agree nor disagree,Neither agree nor disagree,Strongly agree,Neither agree nor disagree,False,False,False,False,True,False,,Somewhat comfortable,Very comfortable,Disagree,False,True,False,False,False,,True,True,False,True,True,False,,I expect it to assist me in completing my task...,True,True,False,True,True,False,,Intermediate,No experience,Beginner,Intermediate,No experience,Beginner,Yes,"to search information and recommendations, i a..."

In [171]:
df1_filtered.to_csv('pre_filtered.csv', index=False)

In [172]:
df2 = pd.read_csv('Post-test 1_August 31, 2024_17.25.csv')
df2.drop([0,1], inplace=True)
df2 = df2[pd.to_datetime(df2['StartDate'], format='%Y-%m-%d %H:%M:%S') > pd.to_datetime('2024-08-23')]
df2.drop(columns=['StartDate','EndDate','Progress','Finished','Status','IPAddress','RecordedDate','ResponseId',
                  'RecipientLastName','RecipientFirstName','RecipientEmail','ExternalReference','LocationLatitude',
                  'LocationLongitude','DistributionChannel','UserLanguage'], axis=1, inplace=True)

tones = ['Friendly', 'Respectful', 'Pushy', 'Bossy', 'Angry', 'Disrespectful', 'Other (input)']
for tone in tones:
    name = {
        'Friendly': 'post_tone_friendly',
        'Respectful': 'post_tone_respectful',
        'Pushy': 'post_tone_pushy',
        'Bossy': 'post_tone_bossy',
        'Angry': 'post_tone_angry',
        'Disrespectful': 'post_tone_disrespectful',
        'Other (input)': 'post_tone_other'
    }.get(tone)
    df2[name] = df2['Q11'].apply(lambda x: 1 if tone in x else 0)
df2.drop(columns=['Q11'], inplace=True)

ordered = ['Q2','Duration (in seconds)','Q3','Q4','Q5','Q6','Q7','Q8','Q9','Q10','post_tone_friendly','post_tone_respectful',
            'post_tone_pushy','post_tone_bossy','post_tone_angry','post_tone_disrespectful','post_tone_other','Q11_7_TEXT',
            'Q42','Q14','Q15','Q16','Q17','Q18','Q19','Q20','Q21','Q22','Q23','Q24','Q25','Q26','Q27','Q28','Q29','Q30',
            'Q31','Q32','Q34','Q35','Q36','Q37','Q38','Q39','Q40','Q41']
df2 = df2[ordered + [ col for col in df2.columns if col not in ordered]]

df2.rename(columns={
    'Q2': 'prolific_id',
    'Duration (in seconds)': 'post_duration',
    'Q3': 'post_agent_helped',
    'Q4': 'post_how_long',
    'Q5': 'post_involvement_satisfied',
    'Q6': 'post_task_was_easy_to_execute',
    'Q7': 'post_first_impression',
    'Q8': 'post_missing_features',
    'Q9': 'post_agent_helped_in_way_as_expected',
    'Q10': 'post_engagement_was_easy',
    'Q11_7_TEXT': 'post_tone_other_details',
    'Q42': 'post_task_complexity',
    'Q14': 'post_agent_assistance_effective_and_not_time_consuming',
    'Q15': 'post_agent_performance',
    'Q16': 'post_technical_issues_or_bugs',
    'Q17': 'post_trust_in_agent_abilities',
    'Q18': 'post_collaboration_was_effective',
    'Q19': 'post_in_which_task_assistance_most_valuable',
    'Q20': 'post_which_task_better_to_be_handled_by_human',
    'Q21': 'post_did_workload_reduced',
    'Q22': 'post_frustrating_or_confusing_part',
    'Q23': 'post_splitting_easy_to_understand',
    'Q24': 'post_steps_order_made_sense',
    'Q25': 'post_instructions_for_step_were_clear',
    'Q26': 'post_decomposition_effectiveness_for_achieving_outcome',
    'Q27': 'post_missing_steps',
    'Q28': 'post_task_delegation_was_clear',
    'Q29': 'post_task_delegation_correctly',
    'Q30': 'post_task_delegation_enough_control',
    'Q31': 'post_task_given_to_human_were_reasonable',
    'Q32': 'post_task_delegation_satisfied',
    'Q34': 'post_effectiveness_compared_to_manual_execution',
    'Q35': 'post_repetitive_actions_automation_enhanced_effectiveness',
    'Q36': 'post_agent_did_its_parts_well',
    'Q37': 'post_outcome_satisfied',
    'Q38': 'post_will_use_in_future_for_similar_tasks',
    'Q39': 'post_improvements_and_feature_ideas',
    'Q40': 'post_will_try_in_future_for_other_tasks',
    'Q41': 'post_overall_satified'
}, inplace=True)

df2.post_tone_other_details.fillna('', inplace=True)
df2.post_technical_issues_or_bugs.fillna('', inplace=True)
df2.post_in_which_task_assistance_most_valuable.fillna('', inplace=True)
df2.post_which_task_better_to_be_handled_by_human.fillna('', inplace=True)
df2.post_did_workload_reduced.fillna('', inplace=True)
df2.post_frustrating_or_confusing_part.fillna('', inplace=True)
df2.post_missing_steps.fillna('', inplace=True)
df2.post_improvements_and_feature_ideas.fillna('', inplace=True)

df2 = df2.astype({
    'prolific_id': 'string',
    'post_duration': 'int32',
    'post_agent_helped': 'category',
    'post_how_long': 'category',
    'post_involvement_satisfied': 'category',
    'post_task_was_easy_to_execute': 'category',
    'post_first_impression': 'string',
    'post_missing_features': 'string',
    'post_agent_helped_in_way_as_expected': 'category',
    'post_engagement_was_easy': 'category',
    'post_tone_friendly': 'bool',
    'post_tone_respectful': 'bool',
    'post_tone_pushy': 'bool',
    'post_tone_bossy': 'bool',
    'post_tone_angry': 'bool',
    'post_tone_disrespectful': 'bool',
    'post_tone_other': 'bool',
    'post_tone_other_details': 'string',
    'post_task_complexity': 'string',
    'post_agent_assistance_effective_and_not_time_consuming': 'category',
    'post_agent_performance': 'category',
    'post_technical_issues_or_bugs': 'string',
    'post_trust_in_agent_abilities': 'string',
    'post_collaboration_was_effective': 'category',
    'post_in_which_task_assistance_most_valuable': 'string',
    'post_which_task_better_to_be_handled_by_human': 'string',
    'post_did_workload_reduced': 'string',
    'post_frustrating_or_confusing_part': 'string',
    'post_splitting_easy_to_understand': 'category',
    'post_steps_order_made_sense': 'category',
    'post_instructions_for_step_were_clear': 'category',
    'post_decomposition_effectiveness_for_achieving_outcome': 'category',
    'post_missing_steps': 'string',
    'post_task_delegation_was_clear': 'bool',
    'post_task_delegation_correctly': 'category',
    'post_task_delegation_enough_control': 'category',
    'post_task_given_to_human_were_reasonable': 'bool',
    'post_task_delegation_satisfied': 'category',
    'post_effectiveness_compared_to_manual_execution': 'category',
    'post_repetitive_actions_automation_enhanced_effectiveness': 'category',
    'post_agent_did_its_parts_well': 'category',
    'post_outcome_satisfied': 'category',
    'post_will_use_in_future_for_similar_tasks': 'category',
    'post_improvements_and_feature_ideas': 'string',
    'post_will_try_in_future_for_other_tasks': 'category',
    'post_overall_satified': 'category'
})

df2.prolific_id.replace({
    '659595564477c6a68a50176e4': '65959564477c6a68a50176e4',
    '60fdd27f77f58d7d8b162870': '60fdd27f77f58d8b162870',
    'test.one@haielab.org, test.two@haielab.or6697fee789563c1c2004ba50': '6697fee789563c1c2004ba50'
}, inplace=True)

df2.head(100)

,prolific_id,post_duration,post_agent_helped,post_how_long,post_involvement_satisfied,post_task_was_easy_to_execute,post_first_impression,post_missing_features,post_agent_helped_in_way_as_expected,post_engagement_was_easy,post_tone_friendly,post_tone_respectful,post_tone_pushy,post_tone_bossy,post_tone_angry,post_tone_disrespectful,post_tone_other,post_tone_other_details,post_task_complexity,post_agent_assistance_effective_and_not_time_consuming,post_agent_performance,post_technical_issues_or_bugs,post_trust_in_agent_abilities,post_collaboration_was_effective,post_in_which_task_assistance_most_valuable,post_which_task_better_to_be_handled_by_human,post_did_workload_reduced,post_frustrating_or_confusing_part,post_splitting_easy_to_understand,post_steps_order_made_sense,post_instructions_for_step_were_clear,post_decomposition_effectiveness_for_achieving_outcome,post_missing_steps,post_task_delegation_was_clear,post_task_delegation_correctly,post_task_delegation_enough_control,post_task_given_to_human_were_reasonable,post_task_delegation_satisfied,post_effectiveness_compared_to_manual_execution,post_repetitive_actions_automation_enhanced_effectiveness,post_agent_did_its_parts_well,post_outcome_satisfied,post_will_use_in_future_for_similar_tasks,post_improvements_and_feature_ideas,post_will_try_in_future_for_other_tasks,post_overall_satified
4,66c8bc6c5b8112a254c5dd9e,1583,Agree,5-10,Disagree,Disagree,It takes too long. Too many words on the scree...,It needs to be a quicker process.,Agree,Disagree,False,True,False,False,False,False,False,,It is not a very complex task.,Strongly disagree,"Fair, no changes requested",No,I trust the ability to execute the tasks accur...,Agree,Finding a time that works for creating the mee...,I prefer tasks to be handled by me because I f...,No. I feel that I can do the task faster.,"Yes, it was confusing to check off boxed in th...",Disagree,Agree,Agree,Ineffective,,True,Appropriate,Disagree,True,Neutral,Worse,Disagree,Acceptable,Satisfied,Not likely at all,"Quicker, and more concise.",Unlikely,Dissatisfied
5,6660ad93734b2991dcb61854,1929,Disagree,5-10,Disagree,Disagree,It was fine.,It couldn't set up the calendar.,Neither agree nor disagree,Strongly agree,True,False,False,False,False,False,False,,I found your directions to be confusing so I h...,Disagree,"Fair, requested changes and experience improved",It could set up the task but it couldn't move ...,not high right now,Neither agree nor disagree,I guess some advice,Yes because I could have finished in one step ...,no it made it more work,I think it was the project that was not helpfu...,Neither agree nor disagree,Agree,Disagree,Ineffective,no I think if I had just been working with the...,True,Neutral,Neither agree nor disagree,True,Neutral,Worse,Neither agree nor disagree,Acceptable,Dissatisfied,Not likely at all,They just have to work out the bugs and when i...,Very unlikely,Neutral
6,613254f907b5038999e2688f,3342,Agree,40-50,Strongly disagree,Strongly disagree,It was very slow and kept repeating actions,no,Neither agree nor disagree,Strongly disagree,False,True,False,False,False,False,False,,I think the agent had any problems and was hav...,Strongly disagree,"Fair, no changes requested",It kept hanging up in it's tasks and repeating...,fter some time it completed the task.,Agree,Setting up the meeting and sending the invitat...,setting up the actual details because the AI w...,no. I kept having to type my answers repeatedly.,It just kept repeating the same tasks over and...,Strongly agree,Strongly agree,Strongly agree,Effective,no,True,Very appropriate,Agree,True,Very satisfied,Worse,Agree,Good,Satisfied,Not likely at all,work the bugs out to stop repetitive actions.,Very unlikely,Very dissatisfied
7,60a7c3e1e70934af63664a46,4076,Agree,20-30,Neither agree or disagree,Strongly agree,calm,none,Agree,Agree,True,False,False,False,False,False,False,,it is complex,Agree,"Fair, requested changes and experience improved",no i didnt,60 percent,Agree,all of it,no,"yes it did, it did most of the work, i just ha...",none in particular,Agree,Agree,Neither agree nor disagree,Neutral,no,True,Appropriate,Disagree,True,Dissatisfied,About the same,Agree,Acceptable,Satisfied,Not likely at all,none,Neutral,Dissatisfied
8,60a7c3e1e70934af63664a46,493,Agree,30-40,Agree,Disagree,engaging,none,Agree,Agree,False,True,False,False,False,False,False,,it was really complex,Agree,"Fair, requested changes and experience improved",none,about 69 percent,Neither agree nor disagree,all of it,no,i dont think t helped reduce my workload,none,Agree,Agree,Agree,Effective,no,True,Neutral,Agree,True,Neutral,Worse,Neither agree nor disagree,Acceptable,Neutral,Not likely at all,i cant thnk of any,Neutral,Neutral
9,655fa55ae220887674baf9d6,1066,Agree,Less than 5,Agree,Strongly agree,The AI task management paid alot of sense and ...,It would be great if it could be intergrated w...,Agree,Agree,True,True,False,False,False,False,False,,the tasks was not complex,Agree,"Fair, no changes requested",No,I would trust the agent to do what I asked it ...,Strongly agree,Telling me how to create a google calnder. It ...,If I was used to the AI system I would prefer ...,no becuase the task is not automated so I stil...,No.,Agree,Agree,Agree,Effective,No i do not think anything was missing,True,Appropriate,Agree,True,Satisfied,About the same,Neither agree nor disagree,Poor,Neutral,Moderately likely,"To automate google services like google cal, d...",Neutral,Neutral
10,661926a590775b6883608abf,1545,Neither agree nor disagree,5-10,Agree,Agree,I will very good,no,Agree,Agree,False,True,False,False,False,False,False,,it was easy,Agree,"Fair, no changes requested",none,I trust it,Agree,all of the task,no,Yes it did because i did not stress myself,none,Agree,Neither agree nor disagree,Strongly agree,Effective,none,True,Neutral,Agree,True,Neutral,About the same,Neither agree nor disagree,Good,Neutral,Slightly likely,none,Likely,Neutral
11,65c19ae4c48696849a14833a,1237,Neither agree nor disagree,Less than 5,Neither agree or disagree,Neither agree or disagree,I am very confused on this whole task manageme...,Yes more explanations,Neither agree nor disagree,Disagree,True,True,False,False,False,False,False,,I really didn't understand it,Disagree,"Fair, no changes requested",No,A decent amount of trust,Neither agree nor disagree,,,,Yes everythinng,Neither agree nor disagree,Neither agree nor disagree,Strongly disagree,Very ineffective,All of the steps were missing. I wasn't told w...,True,Neutral,Neither agree nor disagree,True,Neutral,About the same,Disagree,Acceptable,Very dissatisfied,Not likely at all,Make things less confusing,Neutral,Neutral
12,666972e46a327205747d90e2,5149,Strongly agree,40-50,Agree,Strongly agree,The Ai task management agent was helpful and i...,The Ai agent should be more interactive,Agree,Strongly agree,True,False,False,False,False,False,False,,The tasks were not so complex,Agree,"Fair, no changes requested",Not at all,I very well trust the AI task management agent,Agree,During the execution phase,No,"Yes, It handled most of the tasks itself",,Strongly agree,Strongly agree,Strongly agree,Very effective,No,True,Appropriate,Agree,True,Satisfied,Much better,Strongly agree,Good,Satisfied,Extremely likely,it should incorporate more collaboration,Very likely,Very satisfied
13,66b22a99e083ae63a2bb8906,3214,Agree,10-20,Agree,Agree,didn't think i would get expected result,no,Agree,Agree,True,True,False,False,False,False,False,,flexible,Agree,"Fair, no changes requested",no,most of it response was accurate in response,Agree,scheduling my weekly activities,Ai os great at tasks,yes scheduling my weekly activities,no,Strongly agree,Strongly agree,Strongly agree,Very effective,no,True,Very appropriate,Strongly agree,True,Satisfied,Much better,Strongly agree,Very good,Very satisfied,Extremely likely,improve it accuracy and it efficiency,Very likely,Very satisfied
14,66be3cc80893ae534ba26cd4,1321,Strongly agree,5-10,Agree,Agree,i dont trust it,no,Agree,Agree,False,True,False,False,False,False,False,,not complex,Agree,"Fair, requested changes and experience improved",no,a little more trusting,Agree,"Assisting new users how to setup, and organizi...",no,yes because the AI task management gave me imm...,no,Agree,Agree,Agree,Effective,no,True,Appropriate,Disagree,True,Satisfied,Better,Neither agree nor disagree,Good,Satisfied,Moderately likely,n.a,Likely,Satisfied
15,5e59a1ef29132108b99fbff8,2045,Disagree,The task is not achieved,Neither agree or disagree,Disagree,The AI agent was unable to make the fixes it n...,No,Agree,Disagree,True,False,False,False,False,False,False,,The tasks were pretty simple,Disagree,"Not fair, requested changes but experience rem...",Agent could not delete tasks or meetings,low,Disagree,"sending invites, because I hate having to clic...",Didn't really care,"no, it made simple tasks more complicated by b...",It couldn't delete mistakes,Agree,Disagree,Agree,Ineffective,No,True,Appropriate,Agree,True,Neutral,Worse,Disagree,Poor,Dissatisfied,Not likely at all,Integrate it better with the systems,Very unlikely,Dissatisfied
16,6698fa3c69edb4bc1a482276,8875,Strongly agree,Less than 5,Neither agree or disagree,Strongly agree,"I was not expecting something like this, but t...",no,Strongly agree,Strongly agree,True,True,False,False,False,False,False,,Not complex at all.,Strongly agree,"Fair, no changes requested",No,Neutral,Strongly agree,Task Organization,No. It's all sorted,"Yes. Instead of doing it one after the other, ...",Not at all,Strongly agree,Strongly agree,Strongly agree,Very effective,No,True,Very appropriate,Agree,True,Very satisfied,Better,NaN,Very good,Very satisfied,Extremely likely,Nothing for now as this left me speechless,Very likely,Very satisfied
17,631ffc3584141f143567f021,3661,Agree,10-20,Disagree,Disagree,After failing to create an event the first thr...,"Problem solving skills, error explanation, and...",Disagree,Disagree,True,True,False,False,False,False,False,,The tasks were basic and could be done by most...,Disagree,"Not fair, requested changes but experience rem...","The agent kept running into an error of ""missi...",Minimal.,Agree,Checking the tasks off the task board because ...,No,No because I had to think of ways to word my r...,The constant hand-holding needed to get the mo...,Disagree,Agree,Neither agree nor disagree,Neutral,,True,Neutral,Agree,True,Neutral,Worse,Disagree,Acceptable,Satisfied,Not likely at all,Error workaround.,Neutral,Neutral
18,612517df29cd32c6632b4a44,2594,Disagree,30-40,Disagree,Disagree,It took entirely too long to respond and made ...,It should be as responsive as a personal assis...,Disagree,Strongly disagree,False,True,False,False,False,False,False,,The task was simple but the way the assistant ...,Strongly disagree,"Not fair, requested changes but experience rem...","Yes, the AI first ordered the tasks in the wro...",Low,Disagree,Entering the information in my calendar was go...,I am familiar with Google Calendar and can eas...,Not at all. I just spent over half an hour cre...,I could not get it to list the subtasks in the...,Agree,Agree,Agree,Ineffective,No steps were missing although it did not ask ...,True,Appropriate,Agree,True,Satisfied,Much worse,Strongly disagree,Poor,Very dissatisfied,Not likely at all,It should be seamlessly incorporated into the ...,Very unlikely,Very dissatisfied
19,663463a291e84b2572ef6105,1197,Neither agree nor disagree,5-10,Neither agree or disagree,Agree,"it gave a lot of information to read through, ...","no, but this particaular study i was unable to...",Agree,Agree,False,True,False,False,False,False,False,,"it was fine, seems like it can handle a lot",Agree,"Fair, no changes requested",unable to spell check my reponses,"i use it alot in my day to day life, i like it",Agree,organizing information,it really depends on the task my only concern ...,"in this task i would say maybe, i could have d...",not with AI itself but with this program used ...,Agree,Agree,Agree,Neutral,not really,True,Neutral,Agree,True,Neutral,Better,Agree,Good,Neutral,Moderately likely,"not for AI, but for this study. i was unable t...",Neutral,Neutral
20,6478edcddd5625bacfcd296a,4356,Agree,20-30,Agree,Agree,It was fair enough,Not anything I could think of,Agree,Agree,False,True,False,False,False,False,False,,I didn't see anything complex about the task. ...,Agree,"Fair, no changes requested",,I can count on it for a speedy work,Agree,"The calendar and the Taskboard,how it was exec...",No,I would have been putting everything on the ta...,No,Agree,Agree,Agree,Very effective,,True,Appropriate,Agree,True,Satisfied,Much better,Agree,Very good,Very satisfied,Extremely likely,,Likely,Satisfied
21,60fdd27f77f58d8b162870,1685,Strongly disagree,20-30,Strongly disagree,Strongly disagree,Horrible organization,I dont use these,Strongly disagree,Strongly disagree,False,False,False,False,False,False,True,,Not hard,Strongly disagree,"Not fair, requested changes but experience rem...","This whole project was so laggy, horrible expe...",No trust,Strongly disagree,N.A,Literally all of them,No,Everything,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Very ineffective,,True,Neutral,Neither agree nor disagree,True,Neutral,Much worse,Strongly disagree,Very poor,Very dissatisfied,Not likely at all,,Very unlikely,Very dissatisfied
22,66aeea1cc3ea6ee963f7c515,4016,Strongly agree,40-50,Agree,Agree,Very respectful.,No.,Agree,Agree,True,True,False,False,False,False,False,,These are standard business tasks.,Agree,"Fair, no changes requested",No.,I think the AI task agent was very competent.,Agree,Entering all 6 tasks into the Task Board,"No, really. I think the collaboration was exce...","Yes, the AI task management agent entered manu...",Not really.,Agree,Strongly agree,Agree,Effective,No,True,Appropriate,Agree,True,Very satisfied,About the same,Agree,Very good,Satisfied,Very likely,N/A; it was excellent,Likely,Satisfied
23,668aa70936b52c2937a64944,5270,Agree,More than an hour,Agree,Disagree,it was difficult to navigate,I dont know im confused,Disagree,Disagree,False,False,False,False,False,False,True,it was not user friendly,it was complex,Disagree,"Not fair, requested changes but experience rem...",yes it was slow and it kept regenerating,it was complex,Disagree,No the instructions were not clear,yes,No,Yes it was stating what to but was not able to...,Disagree,Disagree,Strongly disagree,Very ineffective,no,True,Neutral,Strongly disagree,True,Dissatisfied,Worse,Disagree,Acceptable,Dissatisfied,Not likely at all,Make automatic and sync AI with the taskboard ...,Unlikely,Very dissatisfied
24,65959564477c6a68a50176e4,1583,Disagree,10-20,Agree,Strongly disagree,I thought that it worked just like ChatGPT.,I think it's missing a relational aspect.,Disagree,Disagree,False,False,True,False,False,False,True,neutral,They were good but seems like additional tasks...,Disagree,"Not fair, requested changes but experience rem...",Yes - the task management agent page did not a...,I would not trust the AI task management to ex...,Disagree,In the beginning planning process.,I think I could've completed all of the tasks ...,"No, it feels like it created more steps.",The AI task management agent did not address a...,Agree,Disagree,Agree,Neutral,,True,Neutral,Disagree,True,Neutral,Worse,Neither agree nor disagree,Poor,Dissatisfied,Not likely at all,,Unlikely,Dissatisfied
25,5654175604212700054a12b1,1114,Neither agree nor disagree,10-20,Neither agree or disagree,Agree,It is way too slow and doesn't help me at all,None that I can think of,Strongly disagree,Disagree,False,True,False,False,False,False,False,,They were simple,Strongly disagree,"Not fair, requested changes but experience rem...",,Fair,Disagree,Making sure invites were sent,No,No it did not as it did not save me time,The speed of the AI was slow,Disagree,Neither agree nor disagree,Disagree,Ineffective,No,True,Neutral,Agree,True,Neutral,Much worse,Strongly disagree,Acceptable,Satisfied,Not likely at all,To increase speed and lower the amount of steps,Very unlikely,Very dissatisfied
26,66a7e128f37f34ca658be38b,943,Disagree,5-10,Disagree,Disagree,"overkill, i could have done what it could do i...","speed, too much verification",Strongly disagree,Strongly disagree,False,True,False,False,False,False,False,,"very simple, surprised ai took so long",Strongly disagree,"Fair, no changes requested",nope,"confident, but not going to use it because of ...",Agree,"i guess setting up the meetting, thats the onl...",id rather just handle it faster than waiting f...,no- it made me slower,it was insanely slow,Neither agree nor disagree,Agree,Agree,Very ineffective,too many steps,True,Neutral,Neither agree nor disagree,True,Neutral,Much worse,Strongly disagree,Acceptable,Neutral,Not likely at all,just do it instead of 20+ messages,Very unlikely,Dissatisfied
28,5becea624f191100013b438a,1074,Neither agree nor disagree,The task is not achieved,Neither agree or disagree,Neither agree or disagree,I tried using all task mangers in chatgpt tab ...,clearer instruction,Neither agree nor disagree,Neither agree nor disagree,False,False,False,False,False,False,True,didn't get to experience the task management...,didn't get to experience the task management...,Neither agree nor disagree,"Fair, requested changes and experience improved",I tried using all task mangers in chatgpt tab ...,I tried using all task mangers in chatgpt tab ...,Neither agree nor disagree,I tried using all task mangers in chatgpt tab ...,I tried using all task mangers in chatgpt tab ...,I tried using all task mangers in chatgpt tab ...,I tried using all task mangers in chatgpt tab ...,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neutral,,True,Neutral,Neither agree nor disagree,True,Neutral,About the same,Neither agree nor disagree,Very poor,Neutral,Slightly likely,I tried using all task mangers in chatgpt tab ...,Neutral,Neutral
29,66b364ce20ffcd6c959f2aa8,1974,Agree,Less than 5,Agree,Agree,My first impression of the Al task management ...,No,Agree,Agree,False,True,False,False,False,False,False,,The complexity of the tasks were not difficult...,Agree,"Fair, requested changes and experience improved",No I did not.,I completely trust the Al task management agen...,Agree,With adding the meeting to the calendar and se...,No,Yes. Way less data entry for me and much more ...,No.,Strongly disagree,Strongly disagree,Neither agree nor disagree,Neutral,No.,True,Neutral,Neither agree nor disagree,True,Neutral,Better,NaN,Very good,Satisfied,Very likely,,Very likely,Satisfied
30,6697fee789563c1c2004ba50,2472,Agree,20-30,Disagree,Disagree,"I thought it was cool at first, but it quickly...",I think it needs a help option if things start...,Agree,Disagree,True,True,False,False,False,False,False,,Not too complex,Disagree,"Fair, requested changes and experience improved","Yes, the same messages kept being sent to me a...","It's not completely untrustworthy, but I would...",Agree,It was most valuable in marking tasks complete...,"yes, adding the task to the calendar and distr...","No, I ran into technical difficulties so it go...",Just that there were technical difficulties an...,Disagree,Agree,Agree,Effective,No,True,Inappropriate,Agree,True,Dissatisfied,About the same,Neither agree nor disagree,Good,Satisfied,Slightly likely,To work on the technical issues and help with ...,Neutral,Neutral

In [173]:
df2.to_csv('post_full.csv', index=False)

In [174]:
ids = [
    '66c8bc6c5b8112a254c5dd9e',
    '613254f907b5038999e2688f',
    '5e59a1ef29132108b99fbff8',
    '612517df29cd32c6632b4a44',
    '6478edcddd5625bacfcd296a',
    '66aeea1cc3ea6ee963f7c515',
    '668aa70936b52c2937a64944',
    '65959564477c6a68a50176e4',
    '66a7e128f37f34ca658be38b',
    '66454ede84d396a8e86d5b5f'
]
df2_filtered = df2.loc[df2['prolific_id'].isin(ids)]
df2_filtered.head(100)

,prolific_id,post_duration,post_agent_helped,post_how_long,post_involvement_satisfied,post_task_was_easy_to_execute,post_first_impression,post_missing_features,post_agent_helped_in_way_as_expected,post_engagement_was_easy,post_tone_friendly,post_tone_respectful,post_tone_pushy,post_tone_bossy,post_tone_angry,post_tone_disrespectful,post_tone_other,post_tone_other_details,post_task_complexity,post_agent_assistance_effective_and_not_time_consuming,post_agent_performance,post_technical_issues_or_bugs,post_trust_in_agent_abilities,post_collaboration_was_effective,post_in_which_task_assistance_most_valuable,post_which_task_better_to_be_handled_by_human,post_did_workload_reduced,post_frustrating_or_confusing_part,post_splitting_easy_to_understand,post_steps_order_made_sense,post_instructions_for_step_were_clear,post_decomposition_effectiveness_for_achieving_outcome,post_missing_steps,post_task_delegation_was_clear,post_task_delegation_correctly,post_task_delegation_enough_control,post_task_given_to_human_were_reasonable,post_task_delegation_satisfied,post_effectiveness_compared_to_manual_execution,post_repetitive_actions_automation_enhanced_effectiveness,post_agent_did_its_parts_well,post_outcome_satisfied,post_will_use_in_future_for_similar_tasks,post_improvements_and_feature_ideas,post_will_try_in_future_for_other_tasks,post_overall_satified
4,66c8bc6c5b8112a254c5dd9e,1583,Agree,5-10,Disagree,Disagree,It takes too long. Too many words on the scree...,It needs to be a quicker process.,Agree,Disagree,False,True,False,False,False,False,False,,It is not a very complex task.,Strongly disagree,"Fair, no changes requested",No,I trust the ability to execute the tasks accur...,Agree,Finding a time that works for creating the mee...,I prefer tasks to be handled by me because I f...,No. I feel that I can do the task faster.,"Yes, it was confusing to check off boxed in th...",Disagree,Agree,Agree,Ineffective,,True,Appropriate,Disagree,True,Neutral,Worse,Disagree,Acceptable,Satisfied,Not likely at all,"Quicker, and more concise.",Unlikely,Dissatisfied
6,613254f907b5038999e2688f,3342,Agree,40-50,Strongly disagree,Strongly disagree,It was very slow and kept repeating actions,no,Neither agree nor disagree,Strongly disagree,False,True,False,False,False,False,False,,I think the agent had any problems and was hav...,Strongly disagree,"Fair, no changes requested",It kept hanging up in it's tasks and repeating...,fter some time it completed the task.,Agree,Setting up the meeting and sending the invitat...,setting up the actual details because the AI w...,no. I kept having to type my answers repeatedly.,It just kept repeating the same tasks over and...,Strongly agree,Strongly agree,Strongly agree,Effective,no,True,Very appropriate,Agree,True,Very satisfied,Worse,Agree,Good,Satisfied,Not likely at all,work the bugs out to stop repetitive actions.,Very unlikely,Very dissatisfied
15,5e59a1ef29132108b99fbff8,2045,Disagree,The task is not achieved,Neither agree or disagree,Disagree,The AI agent was unable to make the fixes it n...,No,Agree,Disagree,True,False,False,False,False,False,False,,The tasks were pretty simple,Disagree,"Not fair, requested changes but experience rem...",Agent could not delete tasks or meetings,low,Disagree,"sending invites, because I hate having to clic...",Didn't really care,"no, it made simple tasks more complicated by b...",It couldn't delete mistakes,Agree,Disagree,Agree,Ineffective,No,True,Appropriate,Agree,True,Neutral,Worse,Disagree,Poor,Dissatisfied,Not likely at all,Integrate it better with the systems,Very unlikely,Dissatisfied
18,612517df29cd32c6632b4a44,2594,Disagree,30-40,Disagree,Disagree,It took entirely too long to respond and made ...,It should be as responsive as a personal assis...,Disagree,Strongly disagree,False,True,False,False,False,False,False,,The task was simple but the way the assistant ...,Strongly disagree,"Not fair, requested changes but experience rem...","Yes, the AI first ordered the tasks in the wro...",Low,Disagree,Entering the information in my calendar was go...,I am familiar with Google Calendar and can eas...,Not at all. I just spent over half an hour cre...,I could not get it to list the subtasks in the...,Agree,Agree,Agree,Ineffective,No steps were missing although it did not ask ...,True,Appropriate,Agree,True,Satisfied,Much worse,Strongly disagree,Poor,Very dissatisfied,Not likely at all,It should be seamlessly incorporated into the ...,Very unlikely,Very dissatisfied
20,6478edcddd5625bacfcd296a,4356,Agree,20-30,Agree,Agree,It was fair enough,Not anything I could think of,Agree,Agree,False,True,False,False,False,False,False,,I didn't see anything complex about the task. ...,Agree,"Fair, no changes requested",,I can count on it for a speedy work,Agree,"The calendar and the Taskboard,how it was exec...",No,I would have been putting everything on the ta...,No,Agree,Agree,Agree,Very effective,,True,Appropriate,Agree,True,Satisfied,Much better,Agree,Very good,Very satisfied,Extremely likely,,Likely,Satisfied
22,66aeea1cc3ea6ee963f7c515,4016,Strongly agree,40-50,Agree,Agree,Very respectful.,No.,Agree,Agree,True,True,False,False,False,False,False,,These are standard business tasks.,Agree,"Fair, no changes requested",No.,I think the AI task agent was very competent.,Agree,Entering all 6 tasks into the Task Board,"No, really. I think the collaboration was exce...","Yes, the AI task management agent entered manu...",Not really.,Agree,Strongly agree,Agree,Effective,No,True,Appropriate,Agree,True,Very satisfied,About the same,Agree,Very good,Satisfied,Very likely,N/A; it was excellent,Likely,Satisfied
23,668aa70936b52c2937a64944,5270,Agree,More than an hour,Agree,Disagree,it was difficult to navigate,I dont know im confused,Disagree,Disagree,False,False,False,False,False,False,True,it was not user friendly,it was complex,Disagree,"Not fair, requested changes but experience rem...",yes it was slow and it kept regenerating,it was complex,Disagree,No the instructions were not clear,yes,No,Yes it was stating what to but was not able to...,Disagree,Disagree,Strongly disagree,Very ineffective,no,True,Neutral,Strongly disagree,True,Dissatisfied,Worse,Disagree,Acceptable,Dissatisfied,Not likely at all,Make automatic and sync AI with the taskboard ...,Unlikely,Very dissatisfied
24,65959564477c6a68a50176e4,1583,Disagree,10-20,Agree,Strongly disagree,I thought that it worked just like ChatGPT.,I think it's missing a relational aspect.,Disagree,Disagree,False,False,True,False,False,False,True,neutral,They were good but seems like additional tasks...,Disagree,"Not fair, requested changes but experience rem...",Yes - the task management agent page did not a...,I would not trust the AI task management to ex...,Disagree,In the beginning planning process.,I think I could've completed all of the tasks ...,"No, it feels like it created more steps.",The AI task management agent did not address a...,Agree,Disagree,Agree,Neutral,,True,Neutral,Disagree,True,Neutral,Worse,Neither agree nor disagree,Poor,Dissatisfied,Not likely at all,,Unlikely,Dissatisfied
26,66a7e128f37f34ca658be38b,943,Disagree,5-10,Disagree,Disagree,"overkill, i could have done what it could do i...","speed, too much verification",Strongly disagree,Strongly disagree,False,True,False,False,False,False,False,,"very simple, surprised ai took so long",Strongly disagree,"Fair, no changes requested",nope,"confident, but not going to use it because of ...",Agree,"i guess setting up the meetting, thats the onl...",id rather just handle it faster than waiting f...,no- it made me slower,it was insanely slow,Neither agree nor disagree,Agree,Agree,Very ineffective,too many steps,True,Neutral,Neither agree nor disagree,True,Neutral,Much worse,Strongly disagree,Acceptable,Neutral,Not likely at all,just do it instead of 20+ messages,Very unlikely,Dissatisfied
32,66454ede84d396a8e86d5b5f,4229,Strongly agree,30-40,Neither agree or disagree,Disagree,i think it was interesting.,no,Agree,Agree,True,False,False,False,False,False,False,,it the task was easy but a bit complex for me ...,Agree,"Fair, requested changes and experience improved",there were a few error messages.,i would 70% level of trust,Strongly agree,drafting the messages and dispatching them to ...,no/,"yes, it save me the stress of drafting a messa...",it was a bit confusing from the the start.,Disagree,Neither agree nor disagree,Disagree,Effective,no,True,Appropriate,Strongly agree,True,Satisfied,Better,Agree,Acceptable,Neutral,Very likely,i think i should me allowed to provide the ins...,Likely,Satisfied

In [175]:
df2_filtered.to_csv('post_filtered.csv', index=False)

In [176]:
dfm = pd.merge(df1, df2, how='outer', on='prolific_id')
dfm.head(100)

,prolific_id,gender,ethnicity,ethnicity_other,age,pre_duration,pre_usage_gmail,pre_usage_calendar,pre_usage_drive,pre_usage_maps,pre_usage_tasks,pre_usage_none,pre_usage_other,pre_usage_other_details,pre_hours_per_day,pre_activities,pre_usage_gmail_easy,pre_usage_calendar_easy,pre_usage_drive_easy,pre_usage_maps_easy,pre_usage_tasks_easy,pre_challenge_timemanagement,pre_challenge_coordination,pre_challenge_repetitive,pre_challenge_prioritization,pre_challenge_none,pre_challenge_other,pre_challenge_other_details,pre_used_automation_was_convenient,pre_comfortable_with_idea_of_automation,pre_always_use_AI_if_possible,pre_help_automating_repetitive_tasks,pre_help_providing_task_recommendations,pre_help_assisting_in_task_prioritization,pre_help_dont_know,pre_help_other,pre_help_other_details,pre_used_LLM,pre_benefit_increased_productivity,pre_benefit_better_task_organization,pre_benefit_time_savings,pre_benefit_reduced_workload,pre_benefit_other,pre_benefit_other_details,pre_expectations,pre_used_ai_task_management_agents,pre_foreseen_challenge_learning_curve,pre_foreseen_challenge_trust_in_AI_abilities,pre_foreseen_challenge_integration_with_existing_tools,pre_foreseen_challenge_privacy_security_concerns,pre_foreseen_challenge_other,pre_foreseen_challenge_other_details,pre_expertise_gmail,pre_expertise_calendar,pre_expertise_drive,pre_expertise_maps,pre_expertise_tasks,pre_expertise_chatgpt,pre_used_chatgpt_to_accomplish_tasks,pre_used_chatgpt_purpose,post_duration,post_agent_helped,post_how_long,post_involvement_satisfied,post_task_was_easy_to_execute,post_first_impression,post_missing_features,post_agent_helped_in_way_as_expected,post_engagement_was_easy,post_tone_friendly,post_tone_respectful,post_tone_pushy,post_tone_bossy,post_tone_angry,post_tone_disrespectful,post_tone_other,post_tone_other_details,post_task_complexity,post_agent_assistance_effective_and_not_time_consuming,post_agent_performance,post_technical_issues_or_bugs,post_trust_in_agent_abilities,post_collaboration_was_effective,post_in_which_task_assistance_most_valuable,post_which_task_better_to_be_handled_by_human,post_did_workload_reduced,post_frustrating_or_confusing_part,post_splitting_easy_to_understand,post_steps_order_made_sense,post_instructions_for_step_were_clear,post_decomposition_effectiveness_for_achieving_outcome,post_missing_steps,post_task_delegation_was_clear,post_task_delegation_correctly,post_task_delegation_enough_control,post_task_given_to_human_were_reasonable,post_task_delegation_satisfied,post_effectiveness_compared_to_manual_execution,post_repetitive_actions_automation_enhanced_effectiveness,post_agent_did_its_parts_well,post_outcome_satisfied,post_will_use_in_future_for_similar_tasks,post_improvements_and_feature_ideas,post_will_try_in_future_for_other_tasks,post_overall_satified
0,66c8bc6c5b8112a254c5dd9e,Female,Hispanic or Latino,,18-25,315.0,True,False,True,True,False,False,False,,3,"Work, school, hobby",Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,False,True,False,False,False,False,,Somewhat comfortable,Somewhat comfortable,Disagree,True,True,False,False,False,,True,True,True,True,True,False,,AI task management would help me optimize my t...,False,True,True,True,True,False,,Experienced,Beginner,Experienced,Experienced,No experience,Beginner,Yes,"I have used it to find research, answer questi...",1583.0,Agree,5-10,Disagree,Disagree,It takes too long. Too many words on the scree...,It needs to be a quicker process.,Agree,Disagree,False,True,False,False,False,False,False,,It is not a very complex task.,Strongly disagree,"Fair, no changes requested",No,I trust the ability to execute the tasks accur...,Agree,Finding a time that works for creating the mee...,I prefer tasks to be handled by me because I f...,No. I feel that I can do the task faster.,"Yes, it was confusing to check off boxed in th...",Disagree,Agree,Agree,Ineffective,,True,Appropriate,Disagree,True,Neutral,Worse,Disagree,Acceptable,Satisfied,Not likely at all,"Quicker, and more concise.",Unlikely,Dissatisfied
1,6660ad93734b2991dcb61854,Female,Caucasian or White,,50-60,305.0,True,True,True,False,False,False,False,,2,contacting people and writing to share,Agree,Agree,Agree,Neither agree nor disagree,Neither agree nor disagree,False,False,False,False,False,False,,Somewhat comfortable,Somewhat comfortable,Agree,True,False,False,False,False,,True,True,False,True,False,False,,Help me organize my tasks even take over some ...,False,True,False,True,False,False,,Experienced,Beginner,Intermediate,Beginner,No experience,Intermediate,Yes,"Mostly copy writing, and getting a starting pl...",1929.0,Disagree,5-10,Disagree,Disagree,It was fine.,It couldn't set up the calendar.,Neither agree nor disagree,Strongly agree,True,False,False,False,False,False,False,,I found your directions to be confusing so I h...,Disagree,"Fair, requested changes and experience improved",It could set up the task but it couldn't move ...,not high right now,Neither agree nor disagree,I guess some advice,Yes because I could have finished in one step ...,no it made it more work,I think it was the project that was not helpfu...,Neither agree nor disagree,Agree,Disagree,Ineffective,no I think if I had just been working with the...,True,Neutral,Neither agree nor disagree,True,Neutral,Worse,Neither agree nor disagree,Acceptable,Dissatisfied,Not likely at all,They just have to work out the bugs and when i...,Very unlikely,Neutral
2,661433352944c111887337c4,Female,Caucasian or White,,31-39,300.0,True,True,True,True,False,False,False,,3,"booking client meetings, responding to and sen...",Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,False,False,False,False,False,False,,Neutral,Neutral,Agree,True,True,True,False,False,,True,True,False,True,False,False,,I expect to save a lot of time doing a task th...,True,True,False,True,False,False,,Experienced,Experienced,Experienced,Experienced,Experienced,Intermediate,Yes,ChatGPT helps me write key points from a meeti...,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN
3,613254f907b5038999e2688f,Female,Caucasian or White,,40-49,332.0,True,False,True,True,False,False,False,,1 hour or less,personal,Agree,Neither agree nor disagree,Agree,Strongly agree,Neither agree nor disagree,False,False,True,True,False,False,,Somewhat comfortable,Somewhat comfortable,Agree,False,False,False,True,False,,True,False,True,True,False,False,,help get information quickly,False,False,True,False,True,False,,Intermediate,Beginner,Beginner,Experienced,No experience,Beginner,Yes,Prolofic studies,3342.0,Agree,40-50,Strongly disagree,Strongly disagree,It was very slow and kept repeating actions,no,Neither agree nor disagree,Strongly disagree,False,True,False,False,False,False,False,,I think the agent had any problems and was hav...,Strongly disagree,"Fair, no changes requested",It kept hanging up in it's tasks and repeating...,fter some time it completed the task.,Agree,Setting up the meeting and sending the invitat...,setting up the actual details because the AI w...,no. I kept having to type my answers repeatedly.,It just kept repeating the same tasks over and...,Strongly agree,Strongly agree,Strongly agree,Effective,no,True,Very appropriate,Agree,True,Very satisfied,Worse,Agree,Good,Satisfied,Not likely at all,work the bugs out to stop repetitive actions.,Very unlikely,Very dissatisfied
4,66882c4e8bcda7f9bf988fe1,Female,Caucasian or White,,40-49,291.0,True,False,False,False,False,False,True,,5,"side hustle, hobby",Strongly agree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,False,False,False,False,True,False,,Neutral,Somewhat uncomfortable,Strongly disagree,False,True,False,False,False,,True,False,False,True,False,False,,I'm honestly not sure what to expect.,False,True,False,False,False,False,,Expert,No experience,Beginner,No experience,No experience,Beginner,Yes,Entertainment,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN
5,60a7c3e1e70934af63664a46,Female,Hispanic or Latino,,18-25,898.0,False,False,True,True,False,False,False,,2,work and hobby,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,False,False,True,True,False,False,,Somewhat comfortable,Very comfortable,Neither agree nor disagree,False,True,True,False,False,,True,True,False,True,True,False,,make the workload easy for me,True,False,True,False,False,False,,Experienced,Intermediate,Beginner,Intermediate,Intermediate,Intermediate,Yes,to help with research and asignments,4076.0,Agree,20-30,Neither agree or disagree,Strongly agree,calm,none,Agree,Agree,True,False,False,False,False,False,False,,it is complex,Agree,"Fair, requested changes and experience improved",no i didnt,60 percent,Agree,all of it,no,"yes it did, it did most of the work, i just ha...",none in particular,Agree,Agree,Neither agree nor disagree,Neutral,no,True,Appropriate,Disagree,True,Dissatisfied,About the same,Agree,Acceptable,Satisfied,Not likely at all,none,Neutral,Dissatisfied
6,60a7c3e1e70934af63664a46,Female,Hispanic or Latino,,18-25,898.0,False,False,True,True,False,False,False,,2,work and hobby,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,False,False,True,True,False,False,,Somewhat comfortable,Very comfortable,Neither agree nor disagree,False,True,True,False,False,,True,True,False,True,True,False,,make the workload easy for me,True,False,True,False,False,False,,Experienced,Intermediate,Beginner,Intermediate,Intermediate,Intermediate,Yes,to help with research and asignments,493.0,Agree,30-40,Agree,Disagree,engaging,none,Agree,Agree,False,True,False,False,False,False,False,,it was really complex,Agree,"Fair, requested changes and experience improved",none,about 69 percent,Neither agree nor disagree,all of it,no,i dont think t helped reduce my workload,none,Agree,Agree,Agree,Effective,no,True,Neutral,Agree,True,Neutral,Worse,Neither agree nor disagree,Acceptable,Neutral,Not likely at all,i cant thnk of any,Neutral,Neutral
7,655fa55ae220887674baf9d6,Female,African or Black,,26-30,303.0,True,True,True,False,False,False,False,,More than 8,"Work- using calander, meets, email, drive Hobb...",Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,False,True,True,False,False,False,,Neutral,Neutral,Disagree,True,True,True,False,False,,True,True,True,True,True,False,,I think it will make it easier to complete the...,True,True,False,True,False,False,,Expert,Expert,Expert,Expert,Intermediate,Intermediate,Yes,"To rewrite documents, or to help me come up wi...",1066.0,Agree,Less than 5,Agree,Strongly agree,The AI task management paid alot of sense and ...,It would be great if it could be intergrated w...,Agree,Agree,True,True,False,False,False,False,False,,the tasks was not complex,Agree,"Fair, no changes requested",No,I would trust the agent to do what I asked it ...,Strongly agree,Telling me how to create a google calnder. It ...,If I was used to the AI system I would prefer ...,no becuase the task is not automated so I stil...,No.,Agree,Agree,Agree,Effective,No i do not think anything was missing,True,Appropriate,Agree,True,Satisfied,About the same,Neither agree nor disagree,Poor,Neutral,Moderately likely,"To automate google services like google cal, d...",Neutral,Neutral
8,66c646f6334700d75d30c00e,Female,Mixed Race or Multiracial,,31-39,537.0,True,False,False,False,False,False,False,,3,or sending messages,Agree,Agree,Agree,Strongly agree,Agree,False,True,False,False,False,False,,Very comfortable,Very comfortable,Agree,False,True,True,False,False,,True,True,True,True,True,False,,The should be done perfect,True,False,False,False,False,True,None,Expert,Experienced,Experienced,Experienced,Experienced,Experienced,Yes,To make my work easy,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN
9,661926a590775b6883608abf,Female,African or Black,,50-60,543.0,True,False,False,False,False,False,False,,2,work,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Agree,Neither agree nor disagree,False,True,False,False,False,False,,Neutral,Neutral,Agree,False,False,True,False,False,,False,False,False,True,False,False,,Help me get things done easily,False,False,False,False,True,False,,Intermediate,Experienced,Expert,Beginner,Experienced,Beginner,Yes,For research,1545.0,Neither agree nor disagree,5-10,Agree,Agree,I will very good,no,Agree,Agree,False,True,False,False,False,False,False,,it was easy,Agree,"Fair, no changes requested",none,I trust it,Agree,all of the task,no,Yes it did because i did not stress myself,none,Agree,Neither agree nor disagree,Strongly agree,Effective,none,True,Neutral,Agree,True,Neutral,About the same,Neither agree nor disagree,Good,Neutral,Slightly likely,none,Likely,Neutral
10,667aeef276fec8cbaccdfe24,Female,Caucasian or White,,40-49,354.0,True,True,True,False,False,False,False,,5,work and personal,Agree,Neither agree nor disagree,Agree,Agree,Agree,False,False,False,True,False,False,,Somewhat comfortable,Somewhat comfortable,Neither agree nor disagree,True,True,True,False,False,,True,True,True,True,True,False,,help make things easier for me and my team.,True,False,True,False,True,False,,Experienced,Experienced,Expert,Expert,Experienced,Intermediate,Yes,writing letters or proofing things before they...,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN
11,6317511c1dd0acb82cf4b131,Female,Caucasian or White,,40-49,678.0,True,True,True,True,False,False,False,,2,I use them for appointments with clients and t...,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,False,False,False,False,False,False,,Neutral,Somewhat comfortable,Disagree,True,False,False,False,False,,True,True,True,False,True,False,,I except it to automate some of the processes ...,False,False,False,False,True,False,,Experienced,Experienced,Intermediate,Experienced,Beginner,Intermediate,Yes,Mainly writing different things or with ideas ...,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN
12,65c19ae4c48696849a14833a,Female,African or Black,,31-39,331.0,True,True,True,True,False,False,False,,1 hour or less,"Work and every day life, like using Google Map...",Agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,False,False,False,False,False,False,,Neutral,Somewhat comfortable,Disagree,True,False,True,False,True,Assist in determining how long a task should take,True,True,True,False,False,False,,Help me prioritize my schedule and plan out my...,False,False,True,True,True,False,,Experienced,Experienced,Experienced,Experienced,No experience,Intermediate,Yes,I've used it to help revise my resume,1237.0,Neither agree nor disagree,Less than 5,Neither agree or disagree,Neither agree or disagree,I am very confused on this whole task manageme...,Yes more explanations,Neither agree nor disagree,Disagree,True,True,False,False,False,False,False,,I really didn't understand it,Disagree,"Fair, no changes requested",No,A decent amount of trust,Neither agree nor disagree,,,,Yes everythinng,Neither agree nor disagree,Neither agree nor disagree,Strongly disagree,Very ineffective,All of the steps were missing. I wasn't told w...,True,Neutral,Neither agree nor disagree,True,Neutral,About the same,Disagree,Acceptable,Very dissatisfied,Not likely at all,Make things less confusing,Neutral,Neutral
13,666972e46a327205747d90e2,Male,African or Black,,31-39,1396.0,True,True,True,False,True,False,False,,4,Work and hobby,Strongly agree,Agree,Agree,Strongly agree,Agree,False,True,False,True,False,False,,Very comfortable,Very comfortable,Strongly agree,True,True,True,False,False,,True,True,True,True,True,False,,I expect it to to increase my level of product...,True,False,False,True,True,False,,Expert,Expert,Expert,Experienced,Expert,Experienced,Yes,I use ChatGPT for work inspirations and sugges...,5149.0,Strongly agree,40-50,Agree,Strongly agree,The Ai task management agent was helpful and i...,The Ai agent should be more interactive,Agree,Strongly agree,True,False,False,False,False,False,False,,The tasks were not so complex,Agree,"Fair, no changes requested",Not at all,I very well trust the AI task management agent,Agree,During the execution phase,No,"Yes, It handled most of the tasks itself",,Strongly agree,Strongly agree,Strongly agree,Very effective,No,True,Appropriate,Agree,True,Satisfied,Much better,Strongly agree,Good,Satisfied,Extremely likely,it should incorporate more collaboration,Very likely,Very satisfied
14,5ae06df0cd58990001e4c4f3,Male,Asian,,18-25,288.0,True,False,True,True,False,False,False,,1 hour or less,I use Google applications for school and hobbies.,Strongly agree,NaN,Strongly agree,Strongly agree,NaN,False,False,False,True,False,False,,Somewhat comfortable,Somewhat comfortable,Disagree,True,True,False,False,False,,True,True,False,True,True,False,,I expect the task management agent to provide ...,False,True,False,False,True,False,,Experienced,Beginner,Experienced,Experienced,No experience,Intermediate,Yes,I've used ChatGPT to research topics and edit ...,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN
15,66b22a99e083ae63a2bb8906,Female,African or Black,,50-60,871.0,True,False,True,True,False,False,False,,1 hour or less,work,Strongly agree,Agree,Strongly agree,Strongly agree,Agree,False,False,True,False,False,False,,Neutral,Neutral,Neither agree nor disagree,False,True,False,False,False,,True,False,False,False,True,False,,to reduce the workload,True,False,False,False,True,False,,Experienced,Experienced,Experienced,Experienced,Experienced,Experienced,Yes,for research,3214.0,Agree,10-20,Agree,Agree,didn't think i would get expected result,no,Agree,Agree,True,True,False,False,False,False,False,,flexible,Agree,"Fair, no changes requested",no,most of it response was accurate in response,Agree,scheduling my weekly activities,Ai os great at tasks,yes scheduling my weekly activities,no,Strongly agree,Strongly agree,Strongly agree,Very effective,no,True,Very appropriate,Strongly agree,True,Satisfied,Much better,Strongly agree,Very good,Very satisfied,Extremely likely,improve it accuracy and it efficiency,Very likely,Very satisfied

In [177]:
dfm.to_csv('merged_full.csv', index=False)

In [178]:
ids = [
    '66c8bc6c5b8112a254c5dd9e',
    '613254f907b5038999e2688f',
    '5e59a1ef29132108b99fbff8',
    '612517df29cd32c6632b4a44',
    '6478edcddd5625bacfcd296a',
    '66aeea1cc3ea6ee963f7c515',
    '668aa70936b52c2937a64944',
    '65959564477c6a68a50176e4',
    '66a7e128f37f34ca658be38b',
    '66454ede84d396a8e86d5b5f'
]
dfm_filtered = dfm.loc[dfm['prolific_id'].isin(ids)]
dfm_filtered.head(100)

,prolific_id,gender,ethnicity,ethnicity_other,age,pre_duration,pre_usage_gmail,pre_usage_calendar,pre_usage_drive,pre_usage_maps,pre_usage_tasks,pre_usage_none,pre_usage_other,pre_usage_other_details,pre_hours_per_day,pre_activities,pre_usage_gmail_easy,pre_usage_calendar_easy,pre_usage_drive_easy,pre_usage_maps_easy,pre_usage_tasks_easy,pre_challenge_timemanagement,pre_challenge_coordination,pre_challenge_repetitive,pre_challenge_prioritization,pre_challenge_none,pre_challenge_other,pre_challenge_other_details,pre_used_automation_was_convenient,pre_comfortable_with_idea_of_automation,pre_always_use_AI_if_possible,pre_help_automating_repetitive_tasks,pre_help_providing_task_recommendations,pre_help_assisting_in_task_prioritization,pre_help_dont_know,pre_help_other,pre_help_other_details,pre_used_LLM,pre_benefit_increased_productivity,pre_benefit_better_task_organization,pre_benefit_time_savings,pre_benefit_reduced_workload,pre_benefit_other,pre_benefit_other_details,pre_expectations,pre_used_ai_task_management_agents,pre_foreseen_challenge_learning_curve,pre_foreseen_challenge_trust_in_AI_abilities,pre_foreseen_challenge_integration_with_existing_tools,pre_foreseen_challenge_privacy_security_concerns,pre_foreseen_challenge_other,pre_foreseen_challenge_other_details,pre_expertise_gmail,pre_expertise_calendar,pre_expertise_drive,pre_expertise_maps,pre_expertise_tasks,pre_expertise_chatgpt,pre_used_chatgpt_to_accomplish_tasks,pre_used_chatgpt_purpose,post_duration,post_agent_helped,post_how_long,post_involvement_satisfied,post_task_was_easy_to_execute,post_first_impression,post_missing_features,post_agent_helped_in_way_as_expected,post_engagement_was_easy,post_tone_friendly,post_tone_respectful,post_tone_pushy,post_tone_bossy,post_tone_angry,post_tone_disrespectful,post_tone_other,post_tone_other_details,post_task_complexity,post_agent_assistance_effective_and_not_time_consuming,post_agent_performance,post_technical_issues_or_bugs,post_trust_in_agent_abilities,post_collaboration_was_effective,post_in_which_task_assistance_most_valuable,post_which_task_better_to_be_handled_by_human,post_did_workload_reduced,post_frustrating_or_confusing_part,post_splitting_easy_to_understand,post_steps_order_made_sense,post_instructions_for_step_were_clear,post_decomposition_effectiveness_for_achieving_outcome,post_missing_steps,post_task_delegation_was_clear,post_task_delegation_correctly,post_task_delegation_enough_control,post_task_given_to_human_were_reasonable,post_task_delegation_satisfied,post_effectiveness_compared_to_manual_execution,post_repetitive_actions_automation_enhanced_effectiveness,post_agent_did_its_parts_well,post_outcome_satisfied,post_will_use_in_future_for_similar_tasks,post_improvements_and_feature_ideas,post_will_try_in_future_for_other_tasks,post_overall_satified
0,66c8bc6c5b8112a254c5dd9e,Female,Hispanic or Latino,,18-25,315.0,True,False,True,True,False,False,False,,3,"Work, school, hobby",Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,False,True,False,False,False,False,,Somewhat comfortable,Somewhat comfortable,Disagree,True,True,False,False,False,,True,True,True,True,True,False,,AI task management would help me optimize my t...,False,True,True,True,True,False,,Experienced,Beginner,Experienced,Experienced,No experience,Beginner,Yes,"I have used it to find research, answer questi...",1583.0,Agree,5-10,Disagree,Disagree,It takes too long. Too many words on the scree...,It needs to be a quicker process.,Agree,Disagree,False,True,False,False,False,False,False,,It is not a very complex task.,Strongly disagree,"Fair, no changes requested",No,I trust the ability to execute the tasks accur...,Agree,Finding a time that works for creating the mee...,I prefer tasks to be handled by me because I f...,No. I feel that I can do the task faster.,"Yes, it was confusing to check off boxed in th...",Disagree,Agree,Agree,Ineffective,,True,Appropriate,Disagree,True,Neutral,Worse,Disagree,Acceptable,Satisfied,Not likely at all,"Quicker, and more concise.",Unlikely,Dissatisfied
3,613254f907b5038999e2688f,Female,Caucasian or White,,40-49,332.0,True,False,True,True,False,False,False,,1 hour or less,personal,Agree,Neither agree nor disagree,Agree,Strongly agree,Neither agree nor disagree,False,False,True,True,False,False,,Somewhat comfortable,Somewhat comfortable,Agree,False,False,False,True,False,,True,False,True,True,False,False,,help get information quickly,False,False,True,False,True,False,,Intermediate,Beginner,Beginner,Experienced,No experience,Beginner,Yes,Prolofic studies,3342.0,Agree,40-50,Strongly disagree,Strongly disagree,It was very slow and kept repeating actions,no,Neither agree nor disagree,Strongly disagree,False,True,False,False,False,False,False,,I think the agent had any problems and was hav...,Strongly disagree,"Fair, no changes requested",It kept hanging up in it's tasks and repeating...,fter some time it completed the task.,Agree,Setting up the meeting and sending the invitat...,setting up the actual details because the AI w...,no. I kept having to type my answers repeatedly.,It just kept repeating the same tasks over and...,Strongly agree,Strongly agree,Strongly agree,Effective,no,True,Very appropriate,Agree,True,Very satisfied,Worse,Agree,Good,Satisfied,Not likely at all,work the bugs out to stop repetitive actions.,Very unlikely,Very dissatisfied
18,5e59a1ef29132108b99fbff8,Female,Caucasian or White,,26-30,253.0,True,True,True,True,False,False,True,Google Sheets,3,"persona life and work the most, occasionally f...",Agree,Agree,Agree,Agree,Neither agree nor disagree,False,False,False,False,False,False,,,Somewhat uncomfortable,Disagree,True,False,False,True,False,,True,False,False,True,False,False,,"I hope it will help manage some of the rote, t...",False,False,True,True,True,False,,Experienced,Intermediate,Experienced,Experienced,Beginner,Beginner,Yes,Help draft emails,2045.0,Disagree,The task is not achieved,Neither agree or disagree,Disagree,The AI agent was unable to make the fixes it n...,No,Agree,Disagree,True,False,False,False,False,False,False,,The tasks were pretty simple,Disagree,"Not fair, requested changes but experience rem...",Agent could not delete tasks or meetings,low,Disagree,"sending invites, because I hate having to clic...",Didn't really care,"no, it made simple tasks more complicated by b...",It couldn't delete mistakes,Agree,Disagree,Agree,Ineffective,No,True,Appropriate,Agree,True,Neutral,Worse,Disagree,Poor,Dissatisfied,Not likely at all,Integrate it better with the systems,Very unlikely,Dissatisfied
24,612517df29cd32c6632b4a44,Female,Caucasian or White,,50-60,362.0,True,True,True,False,False,False,False,,3,"All email, calendar for personal schedule, Doc...",Agree,Agree,Agree,Neither agree nor disagree,Neither agree nor disagree,False,False,False,False,True,False,,Somewhat uncomfortable,Neutral,Strongly disagree,True,False,False,False,False,,True,False,False,True,False,False,,Hopefully anticipate my needs correctly and do...,False,False,True,False,False,False,,Experienced,Experienced,Experienced,Intermediate,No experience,Intermediate,Yes,Have conversations and ask for advice and info...,2594.0,Disagree,30-40,Disagree,Disagree,It took entirely too long to respond and made ...,It should be as responsive as a personal assis...,Disagree,Strongly disagree,False,True,False,False,False,False,False,,The task was simple but the way the assistant ...,Strongly disagree,"Not fair, requested changes but experience rem...","Yes, the AI first ordered the tasks in the wro...",Low,Disagree,Entering the information in my calendar was go...,I am familiar with Google Calendar and can eas...,Not at all. I just spent over half an hour cre...,I could not get it to list the subtasks in the...,Agree,Agree,Agree,Ineffective,No steps were missing although it did not ask ...,True,Appropriate,Agree,True,Satisfied,Much worse,Strongly disagree,Poor,Very dissatisfied,Not likely at all,It should be seamlessly incorporated into the ...,Very unlikely,Very dissatisfied
28,6478edcddd5625bacfcd296a,Female,African or Black,,50-60,799.0,True,False,False,False,True,False,False,,3,Work and other personal activities,Agree,Agree,Agree,Agree,Agree,False,False,False,False,False,False,,Very comfortable,Very comfortable,Agree,False,True,False,False,False,,True,True,False,False,False,False,,I expect nothing but the best,True,False,True,False,True,False,,Experienced,Experienced,Experienced,Experienced,Experienced,Beginner,Yes,I used it to generate ideas about things that ...,4356.0,Agree,20-30,Agree,Agree,It was fair enough,Not anything I could think of,Agree,Agree,False,True,False,False,False,False,False,,I didn't see anything complex about the task. ...,Agree,"Fair, no changes requested",,I can count on it for a speedy work,Agree,"The calendar and the Taskboard,how it was exec...",No,I would have been putting everything on the ta...,No,Agree,Agree,Agree,Very effective,,True,Appropriate,Agree,True,Satisfied,Much better,Agree,Very good,Very satisfied,Extremely likely,,Likely,Satisfied
30,66aeea1cc3ea6ee963f7c515,Female,Caucasian or White,,50-60,519.0,True,True,True,True,True,False,True,,6,"Business work, daytrips (maps)",Agree,Agree,Agree,Strongly agree,Agree,False,True,False,True,False,False,,Very comfortable,Very comfortable,Neither agree nor disagree,True,True,False,False,False,,True,True,True,True,True,False,,The AI agent will help streamline some of my m...,False,True,True,True,True,False,,Experienced,Intermediate,Experienced,Experienced,Intermediate,Experienced,Yes,"rewording for memorandum language, resumes, an...",4016.0,Strongly agree,40-50,Agree,Agree,Very respectful.,No.,Agree,Agree,True,True,False,False,False,False,False,,These are standard business tasks.,Agree,"Fair, no changes requested",No.,I think the AI task agent was very competent.,Agree,Entering all 6 tasks into the Task Board,"No, really. I think the collaboration was exce...","Yes, the AI task management agent entered manu...",Not really.,Agree,Strongly agree,Agree,Effective,No,True,Appropriate,Agree,True,Very satisfied,About the same,Agree,Very good,Satisfied,Very likely,N/A; it was excellent,Likely,Satisfied
35,668aa70936b52c2937a64944,Female,African or Black,,40-49,920.0,True,False,True,True,False,False,False,,4,work research,Agree,Agree,Agree,Strongly agree,Agree,False,True,True,False,False,False,,Very comfortable,Very comfortable,Agree,False,True,False,False,False,,True,False,True,True,True,False,,"to help me with better task organization, to h...",True,True,False,False,True,False,,Experienced,Beginner,Intermediate,Experienced,Beginner,Intermediate,Yes,to help in research to help save time to help...,5270.0,Agree,More than an hour,Agree,Disagree,it was difficult to navigate,I dont know im confused,Disagree,Disagree,False,False,False,False,False,False,True,it was not user friendly,it was complex,Disagree,"Not fair, requested changes but experience rem...",yes it was slow and it kept regenerating,it was complex,Disagree,No the instructions were not clear,yes,No,Yes it was stating what to but was not able to...,Disagree,Disagree,Strongly disagree,Very ineffective,no,True,Neutral,Strongly disagree,True,Dissatisfied,Worse,Disagree,Acceptable,Dissatisfied,Not likely at all,Make automatic and sync AI with the taskboard ...,Unlikely,Very dissatisfied
37,65959564477c6a68a50176e4,Female,African or Black,,18-25,274.0,True,False,True,True,False,False,False,,8,work and volunteering,Agree,Agree,Strongly agree,Strongly agree,Neither agree nor disagree,False,True,False,True,False,False,,Very comfortable,Very comfortable,Disagree,True,True,True,False,False,,True,True,True,False,False,False,,Help make recommendations for task prioritizat...,False,True,False,False,True,False,,Expert,Expert,Expert,Expert,No experience,Beginner,Yes,editing emails and providing ideas.,1583.0,Disagree,10-20,Agree,Strongly disagree,I thought that it worked just like ChatGPT.,I think it's missing a relational aspect.,Disagree,Disagree,False,False,True,False,False,False,True,neutral,They were good but seems like additional tasks...,Disagree,"Not fair, requested changes but experience rem...",Yes - the task management agent page did not a...,I would not trust the AI task management to ex...,Disagree,In the beginning planning process.,I think I could've completed all of the tasks ...,"No, it feels like it created more steps.",The AI task management agent did not address a...,Agree,Disagree,Agree,Neutral,,True,Neutral,Disagree,True,Neutral,Worse,Neither agree nor disagree,Poor,Dissatisfied,Not likely at all,,Unlikely,Dissatisfied
41,66a7e128f37f34ca658be38b,Male,Caucasian or White,,18-25,163.0,True,False,True,True,True,False,False,,3,Work,Strongly agree,Agree,Disagree,Agree,Agree,False,False,False,False,False,False,,Neutral,Very comfortable,Agree,True,False,False,False,False,,True,True,False,False,False,False,,Come up with action items and streamline my wo...,False,False,True,False,False,False,,Experienced,Intermediate,Intermediate,Experienced,Experienced,Beginner,No,,943.0,Disagree,5-10,Disagree,Disagree,"overkill, i could have done what it could do i...","speed, too much verification",Strongly disagree,Strongly disagree,False,True,False,False,False,False,False,,"very simple, surprised ai took so long",Strongly disagree,"Fair, no changes requested",nope,"confident, but not going to use it because of ...",Agree,"i guess setting up the meetting, thats the onl...",id rather just handle it faster than waiting f...,no- it made me slower,it was insanely slow,Neither agree nor disagree,Agree,Agree,Very ineffective,too many steps,True,Neutral,Neither agree nor disagree,True,Neutral,Much worse,Strongly disagree,Acceptable,Neutral,Not likely at all,just do it instead of 20+ messages,Very unlikely,Dissatisfied
49,66454ede84d396a8e86d5b5f,Male,African or Black,,18-25,844.0,True,False,False,True,False,False,False,,1 hour or less,"to search for information, and GPS Location. a...",Agree,Neither agree nor disagree,Neither agree nor disagree,Strongly agree,Neither agree nor disagree,False,False,False,False,True,False,,Somewhat comfortable,Very comfortable,Disagree,False,True,False,False,False,,True,True,False,True,True,False,,I expect it to assist me in completing my task...,True,True,False,True,True,False,,Intermediate,No experience,Beginner,Intermediate,No experience,Beginner,Yes,"to search information and recommendations, i a...",4229.0,Strongly agree,30-40,Neither agree or disagree,Disagree,i think it was interesting.,no,Agree,Agree,True,False,False,False,False,False,False,,it the task was easy but a bit complex for me ...,Agree,"Fair, requested changes and experience improved",there were a few error messages.,i would 70% level of trust,Strongly agree,drafting the messages and dispatching them to ...,no/,"yes, it save me the stress of drafting a messa...",it was a bit confusing from the the start.,Disagree,Neither agree nor disagree,Disagree,Effective,no,True,Appropriate,Strongly agree,True,Satisfied,Better,Agree,Acceptable,Neutral,Very likely,i think i should me allowed to provide the ins...,Likely,Satisfied

In [179]:
dfm_filtered.to_csv('merged_filtered.csv', index=False)